-- HRMS Database Schema - SQLite Version
-- SQLite-compatible version of the HRMS schema

-- Enable foreign key support (must be set for each connection)
PRAGMA foreign_keys = ON;

-- Note: SQLite uses different data types than Oracle:
-- NUMBER -> INTEGER or REAL
-- VARCHAR2 -> TEXT
-- CHAR -> TEXT
-- DATE -> TEXT (stored as ISO 8601: YYYY-MM-DD)

CREATE TABLE REGIONS (
    REGION_ID INTEGER NOT NULL,
    REGION_NAME TEXT,
    PRIMARY KEY (REGION_ID)
);

CREATE TABLE COUNTRIES (
    COUNTRY_ID TEXT NOT NULL,
    COUNTRY_NAME TEXT,
    REGION_ID INTEGER,
    PRIMARY KEY (COUNTRY_ID),
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

CREATE TABLE LOCATIONS (
    LOCATION_ID INTEGER NOT NULL,
    STREET_ADDRESS TEXT,
    POSTAL_CODE TEXT,
    CITY TEXT NOT NULL,
    STATE_PROVINCE TEXT,
    COUNTRY_ID TEXT,
    PRIMARY KEY (LOCATION_ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INTEGER NOT NULL,
    DEPARTMENT_NAME TEXT NOT NULL,
    MANAGER_ID INTEGER,
    LOCATION_ID INTEGER,
    PRIMARY KEY (DEPARTMENT_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
    -- Manager FK will be added after EMPLOYEES table creation
);

CREATE TABLE JOBS (
    JOB_ID TEXT NOT NULL,
    JOB_TITLE TEXT NOT NULL,
    MIN_SALARY REAL,
    MAX_SALARY REAL,
    PRIMARY KEY (JOB_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INTEGER NOT NULL,
    FIRST_NAME TEXT,
    LAST_NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PHONE_NUMBER TEXT,
    HIRE_DATE TEXT NOT NULL,  -- Store as 'YYYY-MM-DD'
    JOB_ID TEXT NOT NULL,
    SALARY REAL,
    COMMISSION_PCT REAL,
    MANAGER_ID INTEGER,
    DEPARTMENT_ID INTEGER,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID INTEGER NOT NULL,
    START_DATE TEXT NOT NULL,  -- Store as 'YYYY-MM-DD'
    END_DATE TEXT NOT NULL,    -- Store as 'YYYY-MM-DD'
    JOB_ID TEXT NOT NULL,
    DEPARTMENT_ID INTEGER,
    PRIMARY KEY (EMPLOYEE_ID, START_DATE),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Note: SQLite does not support ALTER TABLE ADD FOREIGN KEY after table creation
-- for circular dependencies, so DEPARTMENTS.MANAGER_ID FK must be handled via triggers
-- or accepted as a constraint that's checked in application logic.
-- For this practical, the FK is defined in the DEPARTMENTS CREATE TABLE but will only
-- be enforced after EMPLOYEES records exist.
