-- Practical No. 4: Implement SQL queries to perform various DML Commands on HRMS Database

-- Note: Ensure hrms_schema.sql has been run to create the necessary tables before running these DML commands.
-- Please note constraints (foreign keys) require parent records to exist before child records can be inserted.

-- 1. INSERT Data into various tables
INSERT INTO REGIONS (REGION_ID, REGION_NAME) VALUES (1, 'Europe');
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES ('UK', 'United Kingdom', 1);

INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES (1000, '1297 Via Cola di Rie', '00989', 'Roma', NULL, 'UK');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) 
VALUES (10, 'Administration', NULL, 1000);

INSERT INTO JOBS (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) 
VALUES ('AD_ASST', 'Administration Assistant', 3000, 6000);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (200, 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444', TO_DATE('17-SEP-2003', 'DD-MON-YYYY'), 'AD_ASST', 4400, NULL, NULL, 10);

-- Update department to point to newly created employee as manager
UPDATE DEPARTMENTS SET MANAGER_ID = 200 WHERE DEPARTMENT_ID = 10;

-- 2. SELECT Data: Retrieve all fields from EMPLOYEES
SELECT * FROM EMPLOYEES;

-- 3. SELECT Data with specific columns
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES;

-- 4. SELECT Data using Logical Operators (AND, OR, NOT)
SELECT * FROM EMPLOYEES WHERE SALARY > 4000 AND DEPARTMENT_ID = 10;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 10 OR LOCATION_ID = 2000;
SELECT * FROM EMPLOYEES WHERE NOT (SALARY > 5000);

-- 5. SELECT Data using Comparison Operators (BETWEEN, IN, LIKE)
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 3000 AND 5000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (10, 20, 30);
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE 'W%';

-- 6. UPDATE Data: change an existing value
UPDATE EMPLOYEES 
SET SALARY = 4500, PHONE_NUMBER = '515.123.5555' 
WHERE EMPLOYEE_ID = 200;

-- 7. DELETE Data: Remove rows from tables
-- Must set manager_id to NULL to break circular foreign key dependency before deletion
UPDATE DEPARTMENTS SET MANAGER_ID = NULL WHERE DEPARTMENT_ID = 10;

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 200;
DELETE FROM JOBS WHERE JOB_ID = 'AD_ASST';
DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = 10;
DELETE FROM LOCATIONS WHERE LOCATION_ID = 1000;
